stages:
    - build


build:
    stage: build
    image: node:slim

    services:
        - docker:dind

    before_script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d
        - 
