stages:
    - build
    - build-test
    - test


build:
    stage: build
    image: tmaier/docker-compose:latest

    services:
        - docker:dind

    before_script:
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d

build-test:
    stage: build-test
    image: cypress/base:10

    script:
        - cd MyProj-Frontend
        - cypress run
