stages:
    - build
    - test

build:
    stage: build
    image: docker

    services:
        - docker:dind

    before_script:
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d

test:
    stage: test
    image: mariusdamien/devops-un

    script:
        - npm test