test:
    stage: test
    image: docker
    variables:
    services:
        - docker:dind

    before_script:
        - apk add --no-cache python python-dev py-pip libffi-dev openssl-dev gcc libc-dev make
        - pip install docker-compose
        - apk add --no-cache --update nodejs npm
        - npm install
    script:
        - cd MyProj-Backend
        - npm install
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - npm install
        - docker-compose up -d
        - cypress run
