stages:
    - build
    - test

build:
    stage: build
    image: tmaier/docker-compose

    services:
        - docker:dind

    before_script:
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d

test:
    stage: test
    image: mariusdamien/devops-un:first
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .npm/
    before_script:
        - cd MyProj-Frontend
        - npm install
    script:
        - yarn global add serve
        - yarn test
        - yarn build
        - (serve -s build)&
        - yarn run cypress open