test:
    stage: test
    image: docker
    variables:
    services:
        - docker:dind

    before_script:
        - apk --no-cache add curl
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
    script:
        - cd MyProj-Backend
        - npm install
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - npm install
        - docker-compose up -d
        - cypress run
