test:
    stage: test
    image: docker/docker-compose:latest

    services:
        - docker:dind

    before_script:
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d
        - cypress run
