test:
    stage: test
    image: docker
    variables:
    services:
        - docker:dind

    before_script:
        - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl \
         && curl -O https://bootstrap.pypa.io/get-pip.py \
         && python3 get-pip.py \
         && pip install --upgrade six awscli awsebcli
        - pip install docker-compose
        - apk add --no-cache --update nodejs npm
        - npm install
    script:
        - cd MyProj-Backend
        - npm install
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - npm install
        - docker-compose up -d
        - cypress run
