stages:
    - build


build:
    stage: build
    image: tmaier/docker-compose:latest

    services:
        - docker:dind
        - node:slim

    before_script:
        - docker info
        - docker-compose --version

    script:
        - cd MyProj-Backend
        - docker-compose up -d
        - cd ../MyProj-Frontend
        - docker-compose up -d
        - npm cypress
