version: '3.2'

services:

  front:
    build:
      dockerfile: ./MyProj-Frontend/Dockerfile
      context: .
    container_name: front
    ports:
      - '5000:5000'
    command: "npm install;npm run serve"

  yarn:
    build:
      dockerfile: ./MyProj-Backend/Dockerfile
      context: .
    image: yarn
    volumes:
      - ./
    ports:
      - "3000:3000"

  mongo:
      image: mongo
      container_name: mongo
      environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD

  mongo-express:
      env_file: .env
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 3100:3100
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
        - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
        - VCAP_APP_PORT=3100