version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=MONGO_DATABASE  
    volumes:
      - ./dbdata:/data/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27017"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  back:
    image: node:slim
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - $PWD:/app
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    entrypoint:
      - bash
      - -c
      - "cd /app && npm install && yarn start"
    healthcheck:
      test: ["CMD", "curl", "-f", 'http://localhost:${SERVER_PORT}']
      interval: 1m30s
      timeout: 10s
      retries: 3
  redis:
    image: redis
    ports:
      - 6379:6379

volumes: 
  dbdata: