version: "3"
services:
  front:
    image: node:slim
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    entrypoint:
      - bash
      - -c
      - "cd /app && npm start && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3