version: "3"
services:
  front:
    image: node:slim
    depends_on:
      - watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    entrypoint:
      - bash
      - -c
      - "cd /app && npm start && yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true